# Generated by Django 4.2 on 2023-11-07 00:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='egrul',
            field=models.FileField(blank=True, null=True, upload_to=user.models.file_path, verbose_name='Выписка из ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mkd',
            field=models.FileField(blank=True, null=True, upload_to=user.models.file_path, verbose_name='Договор управления МКД'),
        ),
    ]
