# Generated by Django 4.2 on 2023-08-24 15:28

from django.db import migrations, models
import django.db.models.deletion
import processor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя подсудимого')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес подсудимого')),
                ('period', models.CharField(max_length=100, verbose_name='Период задолжности')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма задолжности')),
                ('format', models.CharField(choices=[('Заполнение', 'Заполнение'), ('Суд', 'Суд'), ('Иск', 'Иск')], max_length=20, verbose_name='Формат заявления')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=processor.models.get_upload_path)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.case')),
            ],
        ),
    ]
