# Generated by Django 4.2.7 on 2023-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_case_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='case',
            name='statement',
        ),
    ]
