# Generated by Django 3.2.23 on 2023-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_case_receipt_remove_case_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='template',
            field=models.CharField(choices=[('statement_magistrate', 'Судебный приказ мирового суда'), ('statement_district', 'Судебный приказ районного суда'), ('lowsuit_district', 'Исковое заявление в районный суд')], default='statement_magistrate', max_length=50, verbose_name='Шаблон'),
        ),
    ]
